## Task 1

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [3]:
def testexception():
    try:
        a=5/0
        return 1,a
    except Exception as e:
        return 0,e

In [4]:
testexception()

(0, ZeroDivisionError('division by zero'))

2. Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].<br><br>
Hint: Subject,Verb and Object should be declared in the program as shown below.<br><br>
subjects=["Americans ","Indians"]<br>
verbs=["play","watch"]<br>
objects=["Baseball","Cricket"]<br><br><b>
Output should come as below:<br><br></b>
Americans play Baseball.<br>
Americans play Cricket.<br>
Americans watch Baseball.<br>
Americans watch Cricket.<br>
Indians play Baseball.<br>
Indians play Cricket.<br>
Indians watch Baseball.<br>
Indians watch Cricket.<br>

In [7]:
# Use List Comprehension
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
op = [i+" "+j+" "+k for i in subjects for j in verbs for k in objects]
for i in op:
    print(i)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [8]:
# Use Looping
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+" "+j+" "+k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2:

1. Write a function so that the columns of the output matrix are powers of the input vector.<br><br>
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br><br>
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [29]:
def atv(ipvector,noc=None,increasing=True):
    # Importing numpy package
    import numpy as np
    
    # Converting input argument as array to get the dimension
    ipvector = np.asanyarray(ipvector)
    
    # Check the dimension and it should be one dimension. If not, raise the value error
    if ipvector.ndim != 1:
        raise ValueError("ipvector (Input Vector) must be a one dimensional array")
    
    # Check the number of required columns. If it is None, it will assign length of ipvector to noc
    if noc is None:
        noc=len(ipvector)
    
    # Generate arrays based on noc (number of columns) and transform those
    return np.asanyarray([ipvector**i if increasing else ipvector**(noc-i-1) for i in range(noc)]).T

In [38]:
import numpy as np
x = np.array([1, 2, 3, 4])
atv(x,3)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

In [39]:
import numpy as np
x = np.array([1, 2, 3, 4])
atv(x,3,increasing=False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [40]:
import numpy as np
x = np.array([1, 2, 3, 4])
atv(x)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])